### ISSUE TITLE
sfn does not load configuration from .sfn file

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sfn#4] opened 2015-04-12 22:52 UTC
When initializing `Sfn::Provider` in `CommandModule::Base::InstanceMethods::provider`, Sfn will fail to pull the configuration directives defined in the .sfn file. The knife cloudformation commands appear to work with the old gem config, just not the Sfn portion. 

Modifying def provider to pull credentials from options rather than config appears to resolve this.

**Comment by chrisroberts** [comment] 2015-04-13 14:02
Hi! Could you provide a redacted copy of your `.sfn` file (mainly interested in the key value setup, not the actual values). The config should be running a merge of namespaced config with global config, and that is the behavior I am experiencing locally. Thanks!

**Comment by JonathanSerafini** [comment] 2015-04-13 16:24
... Let's just pretend I never opened this issue ... -_-
No idea what I might have broken yesterday, or how it was only working with the hack.
Sorry for the noise !

**Comment by JonathanSerafini** [comment] 2015-04-13 16:28
Lack of sleep .. still had the hack in place.
## .sfn
```ruby
Configuration.new do
  credentials do
    provider :aws
    aws_access_key_id ENV['AWS_ACCESS_KEY_ID']
    aws_secret_access_key ENV['AWS_SECRET_ACCESS_KEY']
    aws_region ENV['AWS_REGION']
  end
  options.disable_rollback true
end
```

## knife.rb
```ruby
knife[:cloudformation][:credentials] = {
  :provider => :aws,
  :aws_access_key_id => ENV['AWS_ACCESS_KEY_ID'],
  :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
  :aws_region => ENV['AWS_REGION']
}
```

**Comment by chrisroberts** [comment] 2015-04-13 16:35
Okay, so it _is_ working as expected, or it is _not_ working as expected?

**Comment by JonathanSerafini** [comment] 2015-04-13 16:36
Sorry, no it is not working. 
It *does* work if I make the proposed change of using options.
It *seemed* to work since I had forgotten to clean up the hack prior to the initial testing. 
Sorry

**Comment by chrisroberts** [comment] 2015-04-13 16:38
Do you have the latest version installed?

**Comment by JonathanSerafini** [comment] 2015-04-13 16:41
Seem to get the same issue with either :master or :develop branches
Each time it returns : ERROR: ArgumentError: Cannot auto determine :provider value for credentials

**Comment by chrisroberts** [comment] 2015-04-13 16:47
Okay, are you running this within a bundle? What version of `bogo-cli` is being loaded (either via the bundle, or your system if not within a bundle).

**Comment by JonathanSerafini** [comment] 2015-04-13 16:53
Running sfn within a bundle with Gemfile pulling sfn 0.3.2 from git repo. 

### Gemfile.lock
```
    addressable (2.3.8)
    attribute_struct (0.2.16)
    bogo (0.1.18)
      hashie
      multi_json
    bogo-cli (0.1.12)
      bogo (>= 0.1.6)
      bogo-config
      bogo-ui
      slop (~> 3)
    bogo-config (0.1.10)
      attribute_struct
      bogo (>= 0.1.4, < 1.0)
      multi_json
      multi_xml
    bogo-ui (0.1.8)
      bogo
      command_line_reporter
      paint
```

**Comment by chrisroberts** [comment] 2015-04-13 16:54
Awesome, thanks! Give me a few minutes to see if I can reproduce this locally.

**Comment by chrisroberts** [comment] 2015-04-13 16:59
Looks like I have an update in the cli helper lib locally that's causing the discrepancy. Getting everything packed up to ship and an upgrade should solve this.

**Comment by JonathanSerafini** [comment] 2015-04-13 17:01
Awesome, thanks a bunch, looking forward to it !

**Comment by chrisroberts** [comment] 2015-04-13 17:14
Release new version (v0.3.4) which provides the dependency update. Updating your bundle should resolve it. Thanks for reporting this and your patience while getting the issue chased down!

I'm going to close this but please feel free to re-open if you are still experiencing any problems. Thanks!

**Closed by chrisroberts** 2015-04-13 17:14 UTC
