### ISSUE TITLE
Upstream dependencies breaking sfn

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#178] opened 2016-04-05 16:21 UTC
Looks like aws-sdk, which currently installs jmespath 1.2.3, is breaking template rendering. If I pin jsmepath to 1.1.3 in my Gemfile all's well (at least template rendering is, not sure if this will have any consequences to the aws-sdk gem). Is this a problem to fix sfn/sparkle_formation or upstream with the aws-sdk team?

**Comment by chrisroberts** [comment] 2016-04-05 16:26
aws-sdk isn't used by sfn or sparkle_formation. Can you add `--debug` and paste in the stacktrace that's being generated? Thanks!

**Comment by luckymike** [comment] 2016-04-05 16:29
@jimcroft If you're using the aws-availability-zones pack, by chance, please throw an issue there and I'll get it pinned.

**Comment by jimcroft** [comment] 2016-04-05 16:34
Ah, looks like it was a dep I added myself for a registry (think it was copy/pasted from somewhere).

```
require 'aws-sdk-core'
ec2 = ::Aws::EC2::Client.new

SfnRegistry.register(:availability_zones) do
  ec2.describe_availability_zones.availability_zones.map(&:zone_name)
end
```

This is the stack trace when jmespath 1.2.4 is in the bundle

```
$ sfn create test-stack-jimc -f static_instance_group --print-only --debug
[Sfn]: NumberOfInstances [1]:
[Sfn]: DeletionPolicy [Delete]:
[Sfn]: ApplicationSubnetIds: subnet-d8d25a81
ERROR: TypeError: wrong argument type JSON::Pure::Generator::State (expected JSON/Generator/State)
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:366:in `to_json'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:366:in `block in json_transform'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:359:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:359:in `json_transform'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:341:in `to_json'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.6/lib/sparkle_formation/sparkle_formation.rb:714:in `block in compile'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.6/lib/sparkle_formation/sparkle_formation.rb:665:in `compile'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.6/lib/sparkle_formation/sparkle_formation.rb:753:in `nested?'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.1.12/lib/sfn/command_module/template.rb:178:in `load_template_file'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.1.12/lib/sfn/command/create.rb:24:in `execute!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.1.12/bin/sfn:52:in `block (4 levels) in <top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.1.12/bin/sfn:14:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `<main>'
```

Gemfile looks like this
```
source 'https://rubygems.org'

gem 'aws-sdk', '~> 2.1'

gem 'ipaddress', '~> 0.8.2'
gem 'sparkle_formation', '~> 2.1.6'
gem 'sfn', '~> 2.1.12'
```

**Comment by chrisroberts** [comment] 2016-04-05 16:59
Thanks for the stacktrace. The root cause is the difference in underlying JSON library being used. Ran into this awhile ago with batali which makes fixing it easier :)

I'll close this as soon as the sparkle_formation release is out.

**Comment by jimcroft** [comment] 2016-04-05 17:09
Grand! Thanks Chris.

**Comment by chrisroberts** [comment] 2016-04-05 17:33
and released. Thanks for the report @jimcroft !

**Comment by jimcroft** [comment] 2016-04-05 21:06
Thanks Chris. I've bumped my gems to the new releases of sfn and sparkle_formation but am still getting the same issue.

```
$ sfn create test-stack-jimc -f static_instance_group --print-only --debug
[Sfn]: NumberOfInstances [1]:
[Sfn]: DeletionPolicy [Delete]:
[Sfn]: ApplicationSubnetIds: subnet-d8d25a81
ERROR: TypeError: wrong argument type JSON::Pure::Generator::State (expected JSON/Generator/State)
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:366:in `to_json'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:366:in `block in json_transform'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:359:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:359:in `json_transform'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb:341:in `to_json'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:714:in `block in compile'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:665:in `compile'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:753:in `nested?'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.2.0/lib/sfn/command_module/template.rb:178:in `load_template_file'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.2.0/lib/sfn/command/create.rb:24:in `execute!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.2.0/bin/sfn:56:in `block (4 levels) in <top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-2.2.0/bin/sfn:18:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `<main>'
```

**Comment by chrisroberts** [comment] 2016-04-05 21:57
Okay, more information on this here: flori/json#269

**Comment by chrisroberts** [comment] 2016-04-05 22:22
The pragmatic fix:

```ruby
class Fixnum; def to_json; to_s; end; end
```

**Comment by chrisroberts** [comment] 2016-04-06 00:06
@jimcroft Pinning the aws-sdk back should prevent the error. Once that PR above gets merged and released an update will fix the issue. If it doesn't get merged and released for what ever reason, I'll use the "pragmatic fix" and figure out some non-intrusive way to enable it as required. 

Thanks for pinging back about this still being an issue!

**Comment by chrisroberts** [comment] 2016-04-06 16:12
@jimcroft Looking at this more this morning it appears another workaround that doesn't require pinning back the aws-sdk gem (or the jmespath gem) is to add the `json` gem to your bundle. The crux of the issue being that the `require 'json/pure'` is _only_ being run if the `json` gem can't be enabled (which is generally not installed since it's in the stdlib). So adding:

```ruby
gem 'json' #, '~> 1.8'
```

(with the constraint if you want it or maybe a different constraint) to the Gemfile should make get us back to the "not blowing up" state.

**Comment by chrisroberts** [comment] 2016-04-06 17:00
New version of jmespath has been released that fixes the loading issues. So just updating your bundle (or at least updating jmespath in your bundle to the latest version `1.2.4`) will fix everything up. Thanks again for the report!

**Closed by chrisroberts** 2016-04-06 17:00 UTC
Labels: bug, wontfix
